### ISSUE TITLE
Icon Discovery Improvements - Grouping Etc

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign-Site#10]
I feel it may be worth reconsidering the idea of grouped icons for groups which make sense. Things such as `file-variant`, `weather-variant`, `food-variant`, `sport-variant`, etc. This will group similar icons together in the icon list and generally make searching much easier. We can then also create an issue for each of these groups and use that one issue to handle requests for icons to be added to those groups rather than having requests spread out over a ton of separate issues.

**Comment by AlexMichaelUX** [comment]
This sounds great for my icons it could be 'testing-variant'

**Comment by JamesCoyle** [comment]
I like the idea of keeping the page which shows every available icon but it would definitely be nice to add in pages which allow for better icon discovery. We've talked about this before but I feel a system which supports both methods of icon discovery will work best for more people. 

My proposal is a two pronged approach. 

First, perform an audit of all of the current icons and adjust the naming so similar icons can be positioned next to each other with an alphabetical sort. This involves creation of names for generalized icon groups such as file icons, battery icons, emoticon icons, etc. as stated above. This will immediately improve the full list of icons though it's clear not every icon can fit into such a group. 

I would also suggest adding a toggle switch which hides these icon variants, inserts a pseudo-icon representing the group and shows a badge of how many variants it has. This would drastically reduce the number of icons shown in the icon list and should make it easier to locate a particular icon you are looking for. This could be incredibly effective if combined with a list view option that shows all of the icons in a list with their names beside them but has collapsible sections for icon variants. 

Secondly (lower priority), revamp the old and underutilized tag system to create curated icon groups. These are intended to be much broader than the naming based groups and focus more on the use cases of the icons. Such a system would allow for an experience similar to other icon sets available. This could be implemented as a system which allows users to suggest tags as part of the site UI.

**Comment by PeterShaggyNoble** [comment]
I'd definitely be on board for helping out with this, if needed.

If it's any use, here's the list of categories (tags) I have in my "sandbox":
- Arrows
- Date & Time
- Devices & Hardware
- Editing & Formatting
- Files & Folders
- Food & Drink
- Google
- Logos & Brands
- Media Player Controls
- Money & Payments
- Numbers, Letters & Symbols
- Networking
- Nature & Animals
- Places & Landmarks
- Power
- Science & Medicine
- Sport
- Travel & Transport
- Users & Accounts
- Weather

**Comment by Templarian** [comment]
Pictogrammers will be where we manage all the site work in the future. This repository will be archived.

https://github.com/Pictogrammers/Icon-Site/issues
