### ISSUE TITLE
Document Using @mdi/react with a list of icons

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#107]
https://github.com/Templarian/MaterialDesign-React/issues/26

**Comment by dohomi** [comment]
I'd love to see an example. I am using a headless CMS and through an icon picker in my backend a user grabs any icon name from 1000+ mdi icons. Currently I'm loading webfonts and render it though webfonts + css. It would be great if its possible to render SVG on demand inside of a component.

**Comment by Templarian** [comment]
https://github.com/Pictogrammers/Icon-Site/issues/6

Pictogrammers will be where we manage all the site work in the future. This repository will be archived.
