### ISSUE TITLE
Suggested Change to "SVG - Getting Started"

### ISSUE THREAD

**Issue by alexcoroza** [Templarian/MaterialDesign-Site#108]
Well I dont know what to add in the SVG documentation, but for me its almost useless. There is no detailed way on how to use svg files. What I mean is how to use the inline svg(because loading it via img tag will make you unable to change its colors)

**Comment by MrGrigri** [comment]
our site is currently being redeveloped. You can view it [here](https://dev.materialdesignicons.com/). On our new site, you can see the SVG use cased [here](https://dev.materialdesignicons.com/getting-started/svg) and you can see accessibility best practices [here](https://dev.materialdesignicons.com/guide/accessiblility).
