### ISSUE TITLE
[Feature request] Use Algolia for improving search

### ISSUE THREAD

**Issue by ThomasKientz** [Templarian/MaterialDesign-Site#110]
Why don't use Algolia ? 

Search is the biggest feature IMO. 

On v1 a simple search of "right arrow" is very slow and returns no results. Searching through name, description, tags and related terms (like synonyms) would be a massive hit !

[Font Awesome](https://fontawesome.com/icons?d=gallery&q=arrow%20right) is using Algolia.

**Comment by PeterShaggyNoble** [comment]
See also #48

**Comment by Templarian** [comment]
Oh yeah, there are a dozen things wrong with the old site that we'll be improving search is definitely high on the list. Nothing about it was built to handle 4k+ icons. 😄 

https://github.com/algolia/angular-instantsearch Looks like they have an angular solution we can implement.

Need to rewrite most of the dev page first. It was just a rough mockup I threw together to setup the initial templates.

**Comment by ThomasKientz** [comment]
@Templarian [Here](https://github.com/ThomasKientz/mdi) is test project deployed here : https://mdi.netlify.com/

Works great, would be happy to help setting this up if you want :) 

I have used Vue but Angular should be similar !

**Comment by MrGrigri** [comment]
@ThomasKientz, have you looked at our [site](https://dev.materialdesignicons.com/icons) that is in development?

**Comment by Templarian** [comment]
Any help would be great. Angular is quite a bit different as it's more enterprise oriented, but I've already got the basic page wired up (not even close to the final design, this was thrown together in a day a year ago).

http://dev.materialdesignicons.com/icons

Note the endpoint it is using is not optimized and has cache disabled so it's very slow. Just assume that endpoint was instant. There is a very rudimentary search there currently. It just looks at `icon.name` and `icon.aliases` array for matches.

**Comment by Templarian** [comment]
I updated the `master` branch with a larger realistic test size of icons for local use. Local development uses `mock.get.json` files inside of the `api/` folder. We don't use the live server for local dev. 😄

**Comment by Templarian** [comment]
We'll probably need to limit the rendering to lets say 500 with a load more option. The actual rendering of the SVG elements is very slow.
