### ISSUE TITLE
Display target version in add/edit icons view of the backend

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign-Site#112]
One can select a release version (e.g. 4.5.95) when adding a new icon in `/admin/icons`, but the version is not displayed for existing icons anymore.

It would be helpful to have it at least as read-only field on that screen. If possible, it could also allow you to modify the version as long as it was not published yet.

Workarounds:
- See GitHub milestone
- Check `/admin/release`

**Comment by Templarian** [comment]
Going to close this. It's a nice to have, but the amount of work required to add it is not worth it.

If we need this I'll edit the DB directly.
