### ISSUE TITLE
"Getting started" link from homepage is a 404

### ISSUE THREAD

**Issue by geirawsm** [Templarian/MaterialDesign-Site#118]
When entering the "Getting started" link from the mainpage, it opens `https://materialdesignicons.com/getting-started`.
On this page it tries to load `https://github.com/Templarian/MaterialDesign/blob/master/site/getting-started.savvy` which gives a Github 404.

**Comment by Templarian** [comment]
Good catch, oops, broke the redirect to https://dev.materialdesignicons.com/getting-started

Will fix after work.

**Comment by Templarian** [comment]
This will redirect correctly now.
