### ISSUE TITLE
Icon picker in Android app

### ISSUE THREAD

**Issue by joaomgcd** [Templarian/MaterialDesign-Site#12]
I'm looking to implement a materialdesign.com icon picker in my Android apps so I'm looking for the best way to do it without being to hard on your servers.

I saw that the chrome extension uses a special font to let you pick the icon, so maybe that's a good alternative.

Would that be the way to go? Use the font in the android app to render the icons from there? Or do you see a better alternative?

Thanks in advance for any help!

**Comment by Templarian** [comment]
I would go the route of pulling any resources you need from the CDN. The extension actually packages the resources inside of it to further prevent server hits. If you need the SVG files you can get them from the [design](https://materialdesignicons.com/design) page.

https://cdn.materialdesignicons.com/1.7.22/meta.json
https://cdn.materialdesignicons.com/1.7.22/fonts/materialdesignicons-webfont.ttf

Ideally though, not sure the usefulness of an Android application seeing as most people accessing the icons are designers/developers. The new site is being built with mobile devices in mind. The old site is over 2 years old and has very much out grown its size.

**Comment by Templarian** [comment]
I'm going to mark this closed. Know that we will be including a lot of resources in the future for those using the icons in other open source projects and the meta.json files will over time get pretty much everything we store in the database.

**Comment by joaomgcd** [comment]
Thank you! I realize that a new version is coming up, but just to test it out I'll try caching the webfont in my app and then using that to render the icons on the fly. :)

As for the Android app, believe me, you're going to make a lot of people happy with this. Don't know if you're familiar with the [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) app but I create some plugins for it. One of them creates totally customizable notifications. 

The process of using this would be something like [this](https://youtu.be/fwlk2lC-ALc). Only I have access to this version for now, don't worry, but I'll by implementing it the font way later so everyone can use it with minimal server hit. :)

This way everyone will be able to use any of your thousands of icons to customize their notifications. This is huge! :D

Just to clarify, do you think it would be ok for every user downloading the font once from your server, the first time they use the app? Or would you prefer that I include the font in the app myself?

Thanks again for your help!
