### ISSUE TITLE
Suggested Change to "PHP - Getting Started"

### ISSUE THREAD

**Issue by martinhinrichs** [Templarian/MaterialDesign-Site#120]
It would be helpful for Laravel users to include an example on how to register mdi-php with Blade. The simplest version would be to add the following line to the `boot()` function in `app/Providers/AppServiceProvider.php`:

`Blade::directive('mdicon', function($icon) { return Mdi::mdi($icon); });`

It can then be used like this in Blade templates: 
`@mdicon(emoticon-cool)`

Parsing additional arguments would make the directive more complicated, but maybe displaying the svg is enough, as color and size can be set via css.

**Comment by martinhinrichs** [comment]
Never mind, a better option would be to use [blade-svg](https://github.com/Templarian/MaterialDesign-Site/issues/120). Maybe that could be included in the documentation under PHP/Laravel or under "Webfont alternatives".

**Comment by Templarian** [comment]
Closing this item.

> [Pictogrammers/Icon-Site](https://github.com/Pictogrammers/Icon-Site) will be where we manage all the site work in the future. This repository will be archived.
