### ISSUE TITLE
Incredibly annoying home page to 'https://materialdesignicons.com'

### ISSUE THREAD

**Issue by rpullm168** [Templarian/MaterialDesign-Site#121]
Standard macOS Mojave, Chrome latest.  Browsing through icon lists on index page.  Suddenly, the browser scrolls spontaneously to the bottom of the page.  I use the elevator to scroll back up, Suddenly, the browser scrolls spontaneously to the bottom of the page.  Rinse, repeat.  Unbelievably annoying.

**Comment by Templarian** [comment]
Can you try with your extensions turned off. I just tried on my Mac and am not seeing this behavior?

Can't see it on my Windows machine either.

**Comment by Templarian** [comment]
Closing as I haven't gotten more details to reproduce the issue. Let me know and I'll reopen.
