### ISSUE TITLE
copy to clipboard of npm command on production site seems to be broken

### ISSUE THREAD

**Issue by masbaehr** [Templarian/MaterialDesign-Site#133]
Just noticed this small bug

![image](https://user-images.githubusercontent.com/38694044/76906657-be02c800-68a4-11ea-87bd-cf3aaf6f432f.png)

Copied line has a placeholder

https://cdn.materialdesignicons.com/5.0.45/

**Comment by Templarian** [comment]
This is technically a bug in `@mdi/font-build`, but I'll just leave it here until I fix it.

Typo in the template. Thanks good find! Will fix before we do the `5.1.xx` release.

**Comment by Templarian** [comment]
Fixed this typo and updated the NPM package and CDN so that will work shortly.
