### ISSUE TITLE
Suggested Change to "Webpack - Getting Started"

### ISSUE THREAD

**Issue by simonh1000** [Templarian/MaterialDesign-Site#134]
I want to install the icons locally and use them as css classes in a webpack environment. The current webpack instructions seem to foresee something different, which won't work for me as an Elm developer

**Comment by Templarian** [comment]
@simonh1000 We would highly suggest not using the webfont at all. We may need elm specific documentation.

http://dev.materialdesignicons.com/guide/webfont-alternatives

**Comment by Templarian** [comment]
If `elm` can import `@mdi/js` I would suggest using that. I am not familiar with elm though, but quick Google makes me think it's a JS transpiler or sorts.

**Comment by Templarian** [comment]
Closing this item.

> [Pictogrammers/Icon-Site](https://github.com/Pictogrammers/Icon-Site) will be where we manage all the site work in the future. This repository will be archived.
