### ISSUE TITLE
Suggested Change to "Angular - Getting Started"

### ISSUE THREAD

**Issue by mishangunaweera** [Templarian/MaterialDesign-Site#135]
This is no longer works. Shows this error

Access to XMLHttpRequest at 'http://server-ip/api./assets/mdi.svg' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Templarian** [comment]
Are you running it locally? That endpoint only works when running on the actual production box?

Can you link a screenshot of your dev console. Not seeing anything here.

**Comment by mishangunaweera** [comment]
Yes it runs on my local machine. Can you give me a solution to run it for local testing as well? BTW this DEMO also not working right?

https://stackblitz.com/edit/mdi-material-example

**Comment by Templarian** [comment]
The endpoints are closed source unfortunately. So there is no way to hit production data locally.

What exactly are you trying to do. There might be a better way (like we support node scripts etc).

**Comment by mishangunaweera** [comment]
I'm just trying to extend icon library which does not provided by material.io. And i'm already using material-angular icons. I need more icons than material.io.

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/getting-started/angular

I'm still confused. Why are you trying to run the dev website locally? MDI contains all the icons in the stock set. You're not suppose to use material.io + materialdesignicons.com together. It's one or the other.
