### ISSUE TITLE
Suggested Change to "Xamarin - Getting Started"

### ISSUE THREAD

**Issue by geekmedico** [Templarian/MaterialDesign-Site#137]
When adding the Font reference for iOS in App.xaml you should put the font name, not the filename like this
`<On Platform="iOS" Value="Material Design Icons" />`

Otherwise font doesn't load correctly and just displays a question mark

**Comment by Templarian** [comment]
@geekmedico Can you submit a PR to fix this issue. Not familiar with Xamarin myself. Is it just the iOS one that is different?

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/getting-started-xamarin.md

You can do the edit all within github's interface. 👍

**Comment by geekmedico** [comment]
ok, already submitted

**Comment by Templarian** [comment]
@geekmedico https://github.com/Templarian/MaterialDesign-Site/pulls Did you? I don't see any PRs.

**Comment by geekmedico** [comment]
@Templarian no, i used the "edit on github" button at the page. Sorry, I'm really new to git, so i though that was the easiest way

**Comment by Templarian** [comment]
@geekmedico Oh, no problem I can make the change. Is it just that line that needs to be updated?

**Comment by Templarian** [comment]
The android one android and uwp still use the filename?

**Comment by geekmedico** [comment]
@Templarian yes, just iOS line

**Comment by Templarian** [comment]
Updated. Will be reflected once the site rebuilds in ~5 minutes.

Thanks!
