### ISSUE TITLE
Sharable search results

### ISSUE THREAD

**Issue by peteruithoven** [Templarian/MaterialDesign-Site#139]
A lot of times I'd like to share the icons I got as the result of a search term. Currently I'm resorting to screenshots, but I would like to just share a link. 

This would require supporting including a search term in the url, for example:
http://materialdesignicons.com/icons?q=presentation

**Comment by Templarian** [comment]
@peteruithoven Definitely already being considered for the new site.

Btw, sorry for the confusion we'll be taking down pages form the dev site shortly. We're not using Angular for these pages going forward and moved to a vanilla web component / static website approach that we'll be sharing "shortly" (this repo will eventually house the new site and the admin will still be written in Angular).

**Comment by peteruithoven** [comment]
Thanks! I've updated the url

**Comment by Templarian** [comment]
https://github.com/Pictogrammers/Icon-Site/issues/1

Pictogrammers will be where we manage all the site work in the future. This repository will be archived.
