### ISSUE TITLE
Icons no longer recognized in Sketch

### ISSUE THREAD

**Issue by cezar-darac** [Templarian/MaterialDesign-Site#142]
A few months ago, I think when the font name changed from something like "m aterial d esign i cons" to "Material-Design_Icons" all the icons from our projects were no longer linked to a font. If we choose from Sketch to replace missing fonts, by selecting the new font "Material-Design_Icons", all the icons are replaced by something like [?].

Is there a workaround, or do we have to replace manually the icons in hundreds of places?

Thanks!

**Comment by Templarian** [comment]
We never officially supported desktop usage prior to v5. People were just taking the webfont and using it for desktop.

After v5 we provide a Desktop font: https://github.com/Templarian/MaterialDesign-Font

We purposefully moved all codepoints to `F0001+` codepoints. All you basically need to know is we broke everything on purpose to force people to not install the webfont locally. It causes issues if someone installs an old version locally.

`Material Design Icons Desktop` is the font you need to be using.

**Comment by Templarian** [comment]
That preview in the `-Font` repo above also has a fancy copy/paste SVG feature that new site will be getting.

**Comment by cezar-darac** [comment]
Ok, thank you!
