### ISSUE TITLE
Donation System

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#15]
I'm not sure if this something that will ever be added, but we can use this issue to discuss how this would work.

**Comment by JamesCoyle** [comment]
Probably the fairest way to do this would be a slider system that allows the donor to choose where their donation goes. Something similar to Humble Bundle's slider system but with the first slider being for general hosting costs for the project and the rest being for contributors. 

![image](https://cloud.githubusercontent.com/assets/10384436/21374831/7242147a-c721-11e6-9e48-58b6e2bf0eba.png)

The first slider selects what percentage of the donation goes towards project hosting and additional features that may require funds to implement. The remaining percentage is then split across the contributors who each get a slider which defaults based on how many icons that contributor has submitted.
