### ISSUE TITLE
Figma Wireframing (Reply to be added)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign-Site#18]
Is there any shared document for your wireframe or idea of how you want the site to look? If not, have you heard of [Figma](https://www.figma.com/)? It works great with collaboration.

**Comment by Templarian** [comment]
I've used figma a few times it's pretty solid. That might be a great idea. Right now what is deployed is basically plain bootstrap as I focus on functionality.

Give me some time and I'll try and setup something in Figma for us to prototype with.

**Comment by Templarian** [comment]
Okay, share your email here and I'll invite you to the figma team that we'll use to mock things up. Busy at work right now but I created a starting point.

**Comment by MrGrigri** [comment]
I don't know how I feel about putting my email here. Is there a better and more secure way? Maybe Twitter?

**Comment by Templarian** [comment]
Yea, just DM me on twitter (tweet to me if I don't follow you).

**Comment by Templarian** [comment]
https://www.figma.com/file/R3yaQ8x77pAdzbVTeqtRGnGF/Website-Mockups

If anyone wants to view as we mock everything out. 😄

**Comment by r3volution11** [comment]
@Templarian Hook me up bro-ski:  ----------

**Comment by Templarian** [comment]
@r3volution11 You have edit access now.

**Comment by Templarian** [comment]
Closing as we're moving on to mocking up in the dev server.
