### ISSUE TITLE
Navigation Pane

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign-Site#19]
It seems like a lot of pages are being added to the site but are hidden away as the app bar at the top of the design would get too cluttered. How about adding in a standard navigation pane to provide links? On desktop this could be made persistent and on smaller displays the MDI logo could be replaced with the menu icon. This also scales down to mobile where the app bar quick links can be hidden as well as the logo text to leave the menu icon, the logo icon centered, and the GitHub icon.

**Comment by Templarian** [comment]
@JamesCoyle Please look at the mockup, I've started to outline what this will look like:

https://www.figma.com/file/R3yaQ8x77pAdzbVTeqtRGnGF/Website-Mockups?node-id=479%3A510

Let me know if you want access to help out Figma is pretty easy to learn if you're familiar with other UX design tools.

Also most links will be accessible through the resources page. New site's focus is on Icons and Getting started. I'm a developer a little more than a designer, but I'll work on the mockups to show where I'm heading with the design. I'm recoding a lot of the endpoints from scratch at the moment trying to get them to match the new API docs I've shown in the API issue.

**Comment by Templarian** [comment]
Moved the mockups to another design document to keep things cleaner...

https://www.figma.com/file/LV4L05Ormcl5Jg63Y11km0U8/Mobile-Mockups?node-id=1%3A7

**Comment by JamesCoyle** [comment]
I think at the very least it would be better if the resources link used the same system the getting started link does but I prefer UI designs which provide access to the important information in a clear way. I like what you have so far but it seems like some of the less used pages are neglected in the navigation design. 

Things such as the changelog/history, icon request information page, licence information, contact page (if needed), list of contributors, download page, etc. could use a dedicated link in a navigation panel so it is clear at first glance what information the entire site provides. Currently the links are dotted around all over the place so it is not always clear where to find particular things. 

These are the links I'd provide:

Icons
Guides
Changelog
Contributors
Request Icons
Download

About
Licence
Contact

I'll have to look into Figma at a later date though as I'm currently pretty busy.
