### ISSUE TITLE
Add Keywords to Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#22]
(Spinning this off from [#1903](https://github.com/Templarian/MaterialDesign/issues/1903) for discussion here.)

One thing which might be useful to add is keywords; terms people might use to search for an icon but which wouldn't qualify as aliases.

For example, `cigarette` would work as an alias of `smoking` but not necessarily for `smoking-off`. If it were added as a keyword, though, it would allow `smoking-off` to be returned when someone searched for `cigarette`.

**Comment by quentin-st** [comment]
I thinks that's already the case ; even if they aren't displayed on the web UI

**Comment by PeterShaggyNoble** [comment]
Do you know if the data is available anywhere, @chteuchteu? I don't see it in [meta.json](https://cdn.materialdesignicons.com/1.8.36/meta.json) or the [individual JSON files](https://materialdesignicons.com/api/icon/4F013652-22DE-48CF-886B-A0FB995E8B41).

**Comment by quentin-st** [comment]
@PeterShaggyNoble You can look at the `aliases` and `tags` nodes in the meta.json file you provided. I think `aliases` acts as secondary classes (`.mdi-selfie`) while `tags` acts as keywords on the web UI.

**Comment by PeterShaggyNoble** [comment]
The keywords I'm proposing would differ from aliases and tags. Aliases are alternative names for icons, tags are a means of grouping icons together, keywords would be a way of providing additional terms that wouldn't qualify as aliases or tags to help people find the icons they're looking for.

Taking `account-card-details` as an example this time:
- `identification-card` is an alias for that.
- `user` & `person` would be tags.
- `ID` could be a keyword.

(A bad example, I know, as searching for "ID" would return a match on `identification-card` anyway, but hopefully it serves to illustrate what I'm suggesting)

**Comment by Templarian** [comment]
This was added without me remember this. It's called `style` in the system. Only the new endpoints have it.
