### ISSUE TITLE
Search Log

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#23]
Adding a search log to the site could help with future aliasing and [keywording](https://github.com/Templarian/MaterialDesign-Site/issues/22) (if added) as it would allow you to see the (most common) terms people were searching for.

**Comment by JamesCoyle** [comment]
Only concern is privacy. Would need to be noted in a privacy policy.

**Comment by PeterShaggyNoble** [comment]
As long as personal information (including IP address) isn't being gathered, it shouldn't be that big of an issue, but a line in a privacy policy certainly wouldn't hurt.

**Comment by Templarian** [comment]
\*cough\* We already track all of this. lol.

http://templarian.com/2016/12/30/material-design-icons-2016/ You can see the stats for 2016. 😄 

I have google analytics for this. Will try and share this export shortly, working on tools right now for you guys to be able to add aliases/tags/related icons.
