### ISSUE TITLE
Generate GitHub Icon Previews from Path Data

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#25]
We're going to allow GitHub users to create previews very similar to the current previews we have for production icons. This endpoint will simply take SVG path data.

We need a standard approach to approving designs. I'll water mark these with "DRAFT" so people know the difference.

**Comment by JamesCoyle** [comment]
Would be incredibly useful for moderating contributions! Awesome idea.

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/github

This was added earlier today. Let me know if we should tweak it any. Instead of linking inline, just copy and paste the preview.
