### ISSUE TITLE
Chat space for contributors

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign-Site#27]
While not directly related to the site, it would be handy to have a space to chat with other contributors on issues, changes, e.t.c. related to Material Design Icons. :cat2:

**Comment by Templarian** [comment]
IRC or Slack? I'm on IRC 24/7, but if a slack channel is easier I could create one.

**Comment by GreenTurtwig** [comment]
IRC is good with me, use it a bit here and there anyway, although Slack is simpler. Should probably get some more opinions before anything is final though.

**Comment by quentin-st** [comment]
I think that using Slack would be better - I also use IRC, but Slack is sexier & easier to use for newcomers

**Comment by Templarian** [comment]
Kind of agree I use https://www.irccloud.com which is basically IRC slack, but as we grow the contributor base with the new site / documentation I think slack makes more sense.

Plus who doesn't need another slack team. I'll just create one later on today. Still need to keep most discussions in the Issues, but for general chat and feedback it would be nice.

**Comment by Templarian** [comment]
https://join.slack.com/t/materialdesignicons/shared_invite/enQtMjQ2Njk2MzYyODcwLTEyYTRlNjRlNDEzMjQ4ZmEwOWE0YTMyNDEwNDE2YmM4N2VmMTVlYzUzYWYxNjg5YmExNGI2OGVhODU3Njk0YTk

Sitting at a cafe working on the site/icon backlog today. So join and say hi.

Closing the issue, but I have emails for most of the contribution team. Can invite them, or share the link above with them.
