### ISSUE TITLE
Icons - Search and filter icons.

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#3]
The icons page will be a separate page. We need to make the adoption of the icons easier going forward so the home page will be focused on uses and features.
- [ ] Optimize SVG Rendering
- [ ] Scrolling loads only the visible icons
- [ ] Search by name / alias.
- [ ] Filter by tag name.
- [ ] Group by tag name.

**Comment by PeterShaggyNoble** [comment]
Would the [nightly build](https://github.com/Templarian/MaterialDesign/issues/1910) allow you to use the webfont instead of the SVGs for display purposes, reducing the load times & overheads. Then you could just request the SVG data for each icon as needed for downloads, etc.

**Comment by Templarian** [comment]
Yes the nightly webfont would definitely allow that. We'll be using SVG through and caching in IndexedDB. Will show off the the new endpoints shortly, working on page layouts right now.

Initial load time for all the icons is already much faster with the new endpoints. SVG rendering is slow as hell, but will be optimizing things as much as possible.
