### ISSUE TITLE
Discuss Tags

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#35]
Discuss which tags should be added and removed.

We'll be removing the `action` tag. Think of tags as more of categories.

**Comment by PeterShaggyNoble** [comment]
I'd be in favour of dropping Google's categorisations completely and starting from scratch; they're rarely intuitive, frequently inconsistent and often confusing.

A few suggestions from the sandbox for inclusion:

- [x] Account / User
- [x] Brand icons (w/ separate tag for Google products?)
- [x] Date & time
- [x] Files & folders
- [x] Food & drink
- [x] Home automation
- [x] Nature
- [x] Payment
- [x] Places
- [x] Science
- [x] Sport
- [x] Travel & transport
- [x] Weather

**Comment by JamesCoyle** [comment]
I'd add these to that list:
- [x] Arrows/Directional Icons (chevron, menu, etc)
- [x] Emoji/Unicode Characters
- [ ] People (anything with a person in it)
- [x] Device/Technology or something to that effect?

And if there isn't separate UI for variants:
- Circle
- Square
- Outline

I'd maybe suggest having checkboxes to show/hide those though.

**Comment by GreenTurtwig** [comment]
Tansport and vehicles mgiht be tricky. We have various designs for cars and buses, along with a few other vehicles like trains, bicycle, ferry e.t.c. (tractor has also been submitted). We also have several icons relating to car maintenance, a trailer and caravan which wouldn't really fit under a "transport" tag.

**Comment by JamesCoyle** [comment]
Not sure about sport and weather tbh. I think categories should be broad groups of similar icons with smaller groups of icons just using the naming convention such as `weather-xxx`, `battery-xxx`, `file-xxx`. We really should have a think about how to handle that.

Do we want to add sports as `sport-xxx` or just `xxx`? Same for instruments, food and drink, animals etc. For most things like that you want to keep all the icons together in the list so same-prefix naming makes sense but in what cases is same-prefix too limiting but a broader category/tag would work better?

**Comment by Templarian** [comment]
Updated the categories in the admin. You guys should be able to start just tagging icons now.

> *Note:* I deleted all the existing tags, but since there were only 700 we can very quickly add them and more back. I already added 100 in a few minutes.

Please be careful adding tags, the interface is fast, but deleting is still very manual.

**Comment by Templarian** [comment]
There is a bug. I need to order exact text matches first in the icon search or allow it to scroll. 😴

**Comment by PeterShaggyNoble** [comment]
A few for discussion - do we want to add these tags?

**Brand/Logo**
- `android-debug-bridge`
- `android-head`
- `android-studio`
- `google-nearby`
- `google-pages`
- `google-photos`
- `google-physical-web`
- [`language-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=language) (excl. `translate`)
- `youtube-creator-studio`

**Cloud**
- `amazon-clouddrive`
- `one-drive`

**Date/Time**
- [`alarm-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=alarm) (excl. `alarm-bell` & `alarm-light`)
- [`bell-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=bell) (excl. `alarm-bell`)
- [`watch-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=watch)

**[Files/Folders](https://petershaggynoble.github.io/MDI-Sandbox/?categories=files)**
- `file-*-box`
- `file-tree`
- `library-*`
- `note-*`
- `zip-box`

**Food/Drink**
- [`fridge-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=fridge)

**Comment by Templarian** [comment]
Closing this issue as I think all the tag categories are in.

Also there are **1322** tags in the system and growing. I only added like 400 of these so thanks for taking the time to tag icons. This will make the new site that much better for users.
