### ISSUE TITLE
Some tags don't search

### ISSUE THREAD

**Issue by tankerkiller125** [Templarian/MaterialDesign-Site#39]
Some tags can not be searched, a good example would be the Brand \ Logo tag, If you click on this tag from an icon (say twitter) it will just clear the search and go back to being everything. This happens with any tag that has a slash in it, should probably use % encoding or find away to completely remove the slash

**Comment by tankerkiller125** [comment]
After some further searching on the actual site I found that the API is working exactly the way it should, this is a front end issue

**Comment by Templarian** [comment]
Yea, I forgot to go back and update the front end on the current site to use the new tag system. I'll put a fix in tomorrow. The dev server handles this correctly on the new site.

**Comment by Templarian** [comment]
This has been resolved on the current site. For instance https://materialdesignicons.com/tag/developer-languages Which is the tag "Developer / Languages".
