### ISSUE TITLE
Operation "Stop using the webfont"

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#42]
Team... we know the reasons why. But we have to think of ways to stop people from using the webfont.

**Comment by CoDEmanX** [comment]
Release a new version with all icons replaced by 💩 would be a tad too radical I guess

**Comment by quentin-st** [comment]
What's the reason we all know? Asking for a friend

**Comment by Templarian** [comment]
@chteuchteu Webfonts require including the entire package of icons and if we keep adding icons at the rate we're adding them the font will be massive. `123kb` already for the woff2, with 2350 glyphs.

Tree shaking in modern web apps will make sure their apps are not getting larger if they only use a handful of icons. The option of the webfont will always be there, but we're going to try and persuade people to not use the quick and easy solution.

We also have a plan with the team to start adding more modifiers to existing icons. `-edit` `-plus` `-minus`.

**Comment by PeterShaggyNoble** [comment]
I'm severely undercaffeinated so forgive me if I don't explain this too well, hopefully you get the idea.

A lot the usage of the webfont is probably down to its ease-of-use / people's laziness - drop the CSS file in place and you're away. So, we need to make the SVGs as easy to use as popping `<span class="mdi-icon-name"></span>` into your HTML.

The NPM org is one step towards that but, for those not using NPM, we should offer other options that make the icons easy to use. We've made a start already with the work on [`mdi.php`](https://github.com/Templarian/MaterialDesign/issues/3087) but a JavaScript option could also be useful too, whereby people just need to add `<svg data-mdi="icon-name"></svg>` to their HTML and the JS takes care of the rest, adding the `viewBox` attribute and appending a `path` tag. As with the webfont, it could be hosted on the CDN and offered as a download.

One of the drawbacks of this approach, as with `mdi.php` and the webfont, is the need to include the path data for _all_ the icons but a solution to that could be adding a new feature to the site that works similar to the favourites in [the Sandbox](https://petershaggynoble.github.io/MDI-Sandbox/) which would allow people to add or remove icons to their collection, which they could then download in a variety of formats. And using `localStorage` to store people's icon collections and client-side JS to generate the files to be downloaded would minimise any server/database overheads.

**Comment by quentin-st** [comment]
Hi everyone! I developed a solution to get rid of the webfont for some of my PHP projects - tonight I finally decided to make a composer package out of it: https://github.com/chteuchteu/MaterialDesignIcons-PHP/

What do you think?

**Comment by Templarian** [comment]
@chteuchteu Add a `getting-started-php.md` to https://github.com/Templarian/MaterialDesign-Site/tree/master/src/content and submit a PR, so we have it documented. Looks nice!

You might want to also add it to the existing getting-started on the old site.

**Comment by quentin-st** [comment]
@Templarian Awesome, thx! :-)

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/getting-started/webfont
https://dev.materialdesignicons.com/guide/webfont-alternatives

These pages will be used from now on as the documentation we link people to to get them to rethink their choice. The `@mdi/font` has seen a huge spike in downloads lately and I'm worried.
