### ISSUE TITLE
Auto-focus the search field when opening the icons page

### ISSUE THREAD

**Issue by leMaik** [Templarian/MaterialDesign-Site#45]
This is a minor thing, but it would be great if the input field would be focused when navigating to http://dev.materialdesignicons.com/icons 

Saving one click, twice a day. :sweat_smile:

**Comment by Templarian** [comment]
Pictogrammers will be where we manage all the site work in the future. This repository will be archived.

https://github.com/Pictogrammers/Icon-Site/issues
