### ISSUE TITLE
OpenSearch (e.g. Browser Omnibar search) support

### ISSUE THREAD

**Issue by leMaik** [Templarian/MaterialDesign-Site#46]
To make searching icons even easier, please add an [OpenSearch][1] manifest that links to a page with search results.

That way, we could search for icons by typing `dev.materialdesignicons.com <tab> arrow right` in the browser search bar to get the name of that one icon we always forget the name of. :checkered_flag: 

I'd be happy to help implement this, but I don't know how we should handle URLs that contain search terms. Maybe by adding `#search-term-here` to the URL so that the _hash_ can be used client-side? :thinking: 

[1]: http://www.opensearch.org/Documentation/Developer_how_to_guide

**Comment by peteruithoven** [comment]
> The [OpenSearch description format](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document) lets a website describe a search engine for itself, so that a browser or other client application can use that search engine. OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome. 

More info: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

Screenshots of using this in Firefox:
![screenshot from 2019-01-29 18 01 04 2x](https://user-images.githubusercontent.com/523210/51926327-587a2080-23f1-11e9-9e52-d493bc6fe4fc.png)
![screenshot from 2019-01-29 18 00 35 2x](https://user-images.githubusercontent.com/523210/51926330-587a2080-23f1-11e9-9159-c997605e0641.png)
