### ISSUE TITLE
Search Improvments

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#48]
Currently when searching on the icons page keywords must be separated by hyphens (e.g., `account-alert`) but it would probably be more intuitive to also allow them be separated by spaces (e.g., `account alert`).

It would also help if keywords could be entered in any order  (e.g., `alert account`) and also to allow any combination of keywords that appear in either the icon name or its aliases.

**Comment by Templarian** [comment]
So, search term split by `-` or ` ` (space) and treat them the same.
ex: `account-search` = `['account', 'search']`.

Split all `name` and `alias[]` array into a list of unique keywords.
ex: `account-search` `account-find` = `['account', 'search', 'find']

Check if the search term list contains the terms in each icon list.

**Comment by PeterShaggyNoble** [comment]
Exactly, @Templarian 😃 

It's the same way I have the search working in the Sandbox, makes it much easier to find an icon when you can't quite remember the exact name.

**Comment by Templarian** [comment]
Have this coded and unit tested in the new site's component.
