### ISSUE TITLE
Trailing whitespace breaks documentation

### ISSUE THREAD

**Issue by quentin-st** [Templarian/MaterialDesign-Site#51]
Putting a trailing whitespace at the end of a documentation file produces unexpected result.
`trim_trailing_whitespace` rule of .editorconfig should ensure that no such thing gets in our md files, but not all users uses compatible IDEs.

Related: https://github.com/Templarian/MaterialDesign-Site/pull/50#issuecomment-414809053

**Comment by Templarian** [comment]
Fixed it for the `sidebar.md`. Does it break any other files?

(that file is really a lot of specific of a regex parser)

**Comment by Templarian** [comment]
This was resolved.
