### ISSUE TITLE
Check for existence of #carbon element

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#56]
The following line in [`bundle.js`](http://dev.materialdesignicons.com/main.ef753c0c387b7d367f5d.bundle.js) is preventing other JS in the admin from executing as the `#carbon` element doesn't exist in the admin:

    document.getElementById("carbon").appendChild(n)

Adding some sort of conditional to check for the existence of `#carbon` should rectify it.

**Comment by PeterShaggyNoble** [comment]
Turns out that wasn't the problem at all! Although it wouldn't hurt to add the conditional anyway.

**Comment by Templarian** [comment]
No longer using html ids anywhere in the HTML now. Using the correct ElementRef reference.
