### ISSUE TITLE
Ability to select a custom number of icons that goes into mdi.svg

### ISSUE THREAD

**Issue by un33k** [Templarian/MaterialDesign-Site#57]
[x] feature request

Right now, [mdi.svg](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B) contain all the icons. 

This is great when it comes to angular material 2. One time registration ensures that there is only one trip to the backend.

However, it would be great if there is an ability of choosing a subset of icons and combine them into a single custom mdi.svg during build time of angular.

Another usage would be to add country flags to mdi.svg as well.

Also, if we could add the steps that generates [mdi.svg](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)  to the documents.

**Comment by Templarian** [comment]
@un33k It would be slick to have it on the site, but agreed a temporary solution can be to write a quick tutorial of how to generate the `mdi.svg`. 

http://templarian.com/2018/04/13/scripting-with-nodejs-and-material-design-icons/ It will basically be a pre-written script using this similar code.

**Comment by PeterShaggyNoble** [comment]
@un33k, this feature is available in [the Sandbox](https://petershaggynoble.github.io/MDI-Sandbox/) if you're in need of it now. Build a library by viewing icons and adding them to it. When you're done, you can download your library as a single SVG file. You can also add your own, custom icons if you want to keep everything together.

**Comment by un33k** [comment]
@PeterShaggyNoble could you copy the link for uploading custom icon for inclusion in a single private mdi.svg? Couldn't find it.

**Comment by PeterShaggyNoble** [comment]
@un33k, it's "Add Icon" in the options menu of the "My Library" section at the top of the page.

**Comment by un33k** [comment]
@PeterShaggyNoble the **ask** is to access the script that **combines** all the mdi svgs into a **single** mdi.svg.

Such script can then be used to add custom svgs to mdi.svg. (bulk add)

Such script could also be used to combine multiple [flags](https://github.com/lipis/flag-icon-css/tree/master/flags/4x3) svg into a single flags.svg.

This is to ensure that frameworks like Angular (PWA) won't make 256 roundtrips to the backend in order to  load the flag svgs.

**Comment by Templarian** [comment]
Pictogrammers will be where we manage all the site work in the future. This repository will be archived.

https://github.com/Pictogrammers/Icon-Site/issues I'm not sure this is something we'll be supporting.
