### ISSUE TITLE
Improve Android - Getting Started

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#58]
https://dev.materialdesignicons.com/getting-started/android

- [ ] Introduction to vector drawables
- [ ] Explain API version requirements
- [ ] We need to explain real world examples

**Comment by RealWorldApplications** [comment]
I would like to help on this issue. To clarify you are looking for an introductory article about vector drawables with an example?

**Comment by Templarian** [comment]
Exactly. Feel free to reference the official documentation that Google provides also. Link to outside google docs etc. But basically this getting started should give a good starting place for Android developers.

😄 👻

**Comment by RealWorldApplications** [comment]
Okay thank you. I will contact you if I have any other questions. ;)

**Comment by Templarian** [comment]
@RealWorldApplications Someone made a large PR a second ago for that documentation. Make sure you won't have merge conflicts.

**Comment by touficbatache** [comment]
Yes @RealWorldApplications, only update the `Using SVGs` section :smiley:

**Comment by RealWorldApplications** [comment]
Okay thank you
