### ISSUE TITLE
Icon Export API

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#6]
A single endpoint to download any output of the icons in.

``` json
[{
    "id": "",
    "name": null,
    "type": "png",
    "path": [],
    "width": 24,
    "height": 24,
    "padding": 10,
    "paddingTop": 10,
    "paddingRight": 10,
    "paddingBottom": 10,
    "paddingLeft": 10,
    "foreground": "#FFFFFF",
    "foregroundOpacity": 1,
    "background": "#000000",
    "backgroundOpacity": 1,
    "radius": 10,
    "borderWidth": 1,
    "borderColor": "#990000",
    "borderOpacity": 1,
    "borderCap": "round",
    "borderArray": [4, 4],
    "margin": 10,
    "marginTop": 10,
    "marginRight": 10,
    "marginBottom": 10,
    "marginLeft": 10,
    "gridColor": "#F0F0F0",
    "gridOpacity": 1,
    "matteColor": "#FFFFFF",
    "matteOpacity": 1,
}]
```

<sub>1</sub> All undefined/null properties default. Numbers `0`, Colors `transparent`
<sub>2</sub> `path` = array of folder strings. `[]` (default)
<sub>3</sub> `borderCap` = `butt` / `square` / `round` (default)
<sub>4</sub> `borderArray` standard border array. `[1]` (default aka a solid line)
<sub>5</sub> `grid` requires at least 72x72. 24x24 grid size.

If more than one item the icon is assumed to be a zip file.
- [ ] `id` (required)
- [ ] `name` = icon name
- [ ] `path` = []
- [ ] `width` = 24
- [ ] `height` = 24
- [ ] `padding` = 0
- [ ] `paddingTop` = 0
- [ ] `paddingRight` = 0
- [ ] `paddingBottom` = 0
- [ ] `paddingLeft` = 0
- [ ] `foreground` = #000000
- [ ] `foregroundOpacity` = 1
- [ ] `background` = transparent
- [ ] `backgroundOpacity` = 1
- [ ] `radius` = 0
- [ ] `borderWidth` = 0
- [ ] `borderColor` = #000000
- [ ] `borderCap` = round
- [ ] `borderArray` = [1]
- [ ] `margin` = 0
- [ ] `marginTop` = 0
- [ ] `marginRight` = 0
- [ ] `marginBottom` = 0
- [ ] `marginLeft` = 0
- [ ] `gridColor` = #F0F0F0
- [ ] `gridOpacity` = 1
- [ ] `matteColor` = #FFFFFF
- [ ] `matteOpacity` = 1

**Comment by Templarian** [comment]
Started coding this endpoint. This is a fun endpoint since it will handle so much functionality. Coding in the ability for a few different file types. `svg`, `png`, `xaml`, and `vector-drawable`.

The official docs for the API have more details,
https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/api.md

**Comment by splitbrain** [comment]
This is tagged with help wanted, but I can't seem to find the sources? src/api seems to consist of mockups only currently, however parts of the api you describe seem to be in place and working already. Could you give some info about the state of this issue and some pointers where to start with helping?

**Comment by Templarian** [comment]
@splitbrain Mostly the help wanted is for how the endpoint looks and if it has the features you need. Actually have a good chunk of this endpoint coded already.

I won't be opening up the source for these for a while (eventually, but not on the road map until the new site launches). Basically this repo is for the front end (which is going slowly as I am very busy during the summer).

Need to document the database and setup a test environment for contributors.
