### ISSUE TITLE
Suggested Change to "Angular - Getting Started"

### ISSUE THREAD

**Issue by mbeckenbach** [Templarian/MaterialDesign-Site#68]
Please bring back your old getting started article for angular 2+ from the old documentation until you have a final new documentation. The current angular 2+ documentation is not helpful at all.

**Comment by Templarian** [comment]
Thanks for the suggestion. I can copy and paste it from the git history one sec.

**Comment by Templarian** [comment]
Done, copy and pasted the old docs. Oversight, thought we had copied each section. We've only manually updated a few.

The first party component is almost ready, we're very much moving away from the idea of the giant SVG file. But we'll need to keep a section documented for `@mdi/angular-material`.

We could definitely use help improving these docs if you want to submit a Pull Request. The Angular Component will function almost identically to the `@mdi/react` component if you are curious.

**Comment by mbeckenbach** [comment]
Thank you for the fast action.
Will you Continue to provide that huge svg file? It is very helpful für angular material apps where the page load does not matter. (Intranet Apps)
Am 10. Okt. 2018, 16:34 +0200 schrieb Austin Andrews <notifications@github.com>:

**Comment by Templarian** [comment]
Yea, but I would prefer people use NPM. `@mdi/angular-material` is versioned and is more "production" tested. The link in the docs is generated right from the DB with latest.

**Comment by Templarian** [comment]
We'll probably deprecate the ability to download the latest `mdi.svg` and link to the dist repo.

https://github.com/Templarian/MaterialDesign-Angular-Material

Which I just now realized doesn't have `v2.8.94` for some reason. I really need to stop drinking while doing production deploys.

**Comment by mbeckenbach** [comment]
I wasn't aware of that way to include files from node_modules into the assets folder via angular.json.
I agree. That's a much cleaner way than downloading the file directly. 

{ "glob": "mdi.svg", "input": "../node_modules/@mdi/angular-material", "output": "./assets" }
