### ISSUE TITLE
ADA Testing

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign-Site#7]
ADA testing for high level use of the site. Not sure how far we want to take this, but definitely far enough that people can navigate around.
- [ ] Home
- [ ] Icons
- [ ] Guides
- [ ] CoC

**Comment by MrGrigri** [comment]
I would stick with WCAG 2.0 Level AA as a standard, as the DoJ is using it as a settlement for ADA lawsuits.

**Comment by MrGrigri** [comment]
[WCAG 2.0](https://www.w3.org/TR/WCAG20/) as a reference.

**Comment by Templarian** [comment]
Investing a lot of time into the new site, but moving over to new repo.

Pictogrammers will be where we manage all the site work in the future. This repository will be archived.
