### ISSUE TITLE
Suggested Change to "Getting Started"

### ISSUE THREAD

**Issue by cyberalien** [Templarian/MaterialDesign-Site#73]
Hello,

I have developed an alternative to web fonts that supports MDI set. It is open source SVG framework.
Iconify repository: https://github.com/iconify-design/
Page for MDI set: https://iconify.design/icon-sets/mdi/  

I’m hoping you would mention Iconify in Material Design documentation. This commit adds Iconify documentation to your new website: https://github.com/cyberalien/MaterialDesign-Site/commit/1835cc11cf16a7701f87182e0840b4438f396081

Would it be ok to make pull request for that commit?

About Iconify: It is open source SVG framework that works similar to glyph fonts, but renders SVG.

Its main feature is it downloads only icons that are used on page instead of loading entire set of icons. So for example if designer has only few MDI icons on HTML page, Iconify will fetch only those few icons, not entire MDI set. That makes it possible to use Iconify with unlimited number of icons.

Usage is very simple: add script tag to header or footer of document to include Iconify (about 21kb):

```<script src="//code.iconify.design/1/1.0.0-rc1/iconify.min.js"></script>```

then write placeholders for icons:

```<span class="iconify" data-icon="mdi-emoticon-happy"></span>```

There are more usage options. For example you can see instructions on how to use mdi-emoticon-happy with Iconify at https://iconify.design/icon-sets/mdi/emoticon-happy.html

**Comment by Templarian** [comment]
I'm out all weekend due to various Halloween festivities. Can you update the document for the self hosted option.

Also nice work, as you've probably seen our top goal in the new docs is to stop webfont usage (or at least persuade against it).

**Comment by cyberalien** [comment]
Thank you. Self hosting documentation updated.

There are still some empty documentation pages on Iconify website, but I'll take care of that next week. Website has been rewritten in last few weeks to fully automate icons update process, so whenever any designer publishes new icons they appear on Iconify within 24 hours.

Yes, I did see your top goal :)
This was my top goal as well in last few years. Originally I've made Iconify to give more choices to customers using my XenForo styles, but now Iconify has basically overtaken all my development.

**Comment by Templarian** [comment]
One more change, can you convert this to a Guide url. Trying to leave the top getting-started section for Languages/Frameworks.

Submit the PR and I'll try and get it merged this week. 😄 

We'll have some cleaned up cross links between these more than just the sidebar eventually.

**Comment by Templarian** [comment]
Closing this out, will track with the PR (busy at work today since I had yesterday off, but will get to it shortly).
