### ISSUE TITLE
Adding Multiple Aliases

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#75]
The ability to add multiple aliases to an icon in one go would be a handy addition to the site. The easiest way to implement it would probably be to allow the aliasing form to accept a delimited list of aliases.

**Comment by Templarian** [comment]
Contributors now have the ability to add multiple aliases with a comma. Don't worry spaces are now trimmed also.

I'll work on adding more validation shortly to prevent duplicate aliases.
