### ISSUE TITLE
TODO: Bug Jacob to help write ember usage guide

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign-Site#76]
I noticed that you have a documentation stub for how to use your icons with EmberJS apps:
https://github.com/Templarian/MaterialDesign-Site/blob/9bac349e0a87bccd3098cffbb9591b38daf73e4d/src/content/getting-started-ember.md#ember---getting-started
As someone who likes your icons, likes Ember, and likes contributing to open source things when I can afford to do so, I am willing to help with this. If you're reading this and the issue has grown old and stale, please nudge me as I often forget to follow-up with stuff like this unless it's impacting my day-to-day work.

**Comment by Templarian** [comment]
I can definitely do that. Even if you just want to submit a PR for a little of the docs at a time myself or one of the contributors can quickly merge it. Anything is better than nothing.

**Comment by Templarian** [comment]
@jacobq Even if it's just a really simple getting started guide. \**pokes with stick*\*

**Comment by jacobq** [comment]
OK, I'll see how far I can get before my daughter wakes up from her nap :smile: 

(*Edit*: she just woke up so I'm pausing for now)

**Comment by Templarian** [comment]
Closing this issue out, but be sure to come back and make more edits as you have time to refine things. I'll give it a look through once I have time.
