### ISSUE TITLE
GET /api/package/:packageId/version returns PHP error

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign-Site#78]
(Let me know if you don't bug reports for the dev site -- I'm not sure if this is a known issue or not)

Looks like `GET api/package/:packageId/version` [should return a list of versions](https://dev.materialdesignicons.com/contribute/site/api#get-font-versions-by-package-id) but when I fetch the URL below I encounter an error:

https://dev.materialdesignicons.com/api/package/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B/version

> Fatal error: Call to undefined function get_package_icon() in /home/templarian/webapps/materialdesigniconsdev/api/index.php on line 134

**Comment by Templarian** [comment]
I need to get these fixed. It's fine, I rewrote a lot of the endpoints pretty drastically for the new cache stuff, so might have broke some of them. I'll use these to track them.

**Comment by jacobq** [comment]
@Templarian OK. BTW, is [`POST api/download`](https://dev.materialdesignicons.com/contribute/site/api#download-icon) the endpoint you were referring to in https://github.com/Templarian/MaterialDesign-SVG/issues/10#issuecomment-439977737? I'm trying to duct tape together some way of generating a webfont of the latest icons.

**Comment by Templarian** [comment]
http://materialdesignicons.com/custom You could just use the CSV export tool.

**Comment by jacobq** [comment]
Ah, thank you. I didn't understand what that did -- now I see that it gives templated (e.g. CSV) output of icon data. So to get something close to JSON I can do:

start = `{ icons: [`
loop =
```
{
  name: '{name}',
  author: '{author}',
  path:"{data}"
}, 
```
end = `]}`

I'm not quite sure how to get that into a webfont yet, but it seems better than the hack I had made before to rip the SVG from the site: 

```js
// Paste in console of https://dev.materialdesignicons.com/icons
const msDelayBetweenDownloads = 100;
const width = 24;
const height = width;

const serializer = new XMLSerializer();
const a = document.createElement("a");
a.setAttribute('target', '_blank');
a.setAttribute('onclick', function(e) { e.stopPropagation(); e.preventDefault(); });
document.body.appendChild(a);

Array.from(document.querySelectorAll('mdi-icons a.icon[href]'))
.forEach((a, i) => setTimeout(() => {

    const name = a.href.split('/').slice(-1)[0];
    const svg = a.querySelector('svg');
    const svgString = serializer.serializeToString(svg).replace(/_ngcontent-c3=""\s*/ig, '');

    const svgFileData = `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">${svgString}`;

    console.log(name, svgFileData);
    const file = 'data:image/svg+xml;charset=utf-8,' + svgFileData;
    a.href = file;
    a.download = name;
    a.click();
}, i*msDelayBetweenDownloads));
```

**Comment by Templarian** [comment]
We're closing all issues as I move to the new repo, versions are tied to fonts, so it can be gotten from this endpoint.

`https://dev.materialdesignicons.com/api/admin/package/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B/font`

Packages can have multiple fonts.
