### ISSUE TITLE
Suggest Visually Similar Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#79]
Work is already underway on displaying *related* icons on each icon's page, based on a manual selection process but showing visually similar icons could be useful as well.

@darosh already has this implemented on his [Material Icons Bundle](https://darosh.github.io/material-icons-bundle/) site ([example](https://darosh.github.io/material-icons-bundle/#/?icon=access_point) and looking through the code (see links below), it looks like, rather then directly comparing the path data, he's rendering the SVGs as PNGs and then comparing the pixel data to build the list of similar icons.

**Relevant Files:**
- [loadCommunity.js](https://github.com/darosh/material-icons-bundle/blob/master/build/lib/loadCommunity.js) - builds the JSON file of icon data (which we obviosuly already have available through the API)
- [renderSvg.js](https://github.com/darosh/material-icons-bundle/blob/master/build/lib/renderSvg.js) - renders the SVGs as PNGs via [this file](https://github.com/darosh/material-icons-bundle/blob/master/build/render.js) with references to [this file](https://github.com/darosh/material-icons-bundle/blob/master/build/config/render.conf.js) and [this package](https://www.npmjs.com/package/sharp)
- [compare.js](https://github.com/darosh/material-icons-bundle/blob/master/build/compare.js) - compares the PNGs and builds the collections of similar icons.

**Comment by darosh** [comment]
@PeterShaggyNoble The internal rendering pipeline in MIB goes from SVG -> PNG RGBA -> Grayscale -> Threshold(224) -> Black&White hexadecimal hash:
`"000000000000000000000000000000008ff000cff100c89181c89181c89181cff1ff8ff0ff000081eff381fff78930ee0810cc08ffff08ffff000000000000000000000000000000"` (4 pixels in each character) then the differing bits are counted for each hash pair (with some optimization based on number of pixels and max distance skipping too different icons.)

**Comment by darosh** [comment]
@PeterShaggyNoble ~~refactoring WIP~~ refactored into standalone, optimized lib: https://github.com/darosh/similar-icons

```
> node example.js

Rendering...
[■■■■■■■■■■] 100% | 1s | 3039/3039 | 21s
Saving... example-hashes.json
Comparing...
[■■■■■■■■■■] 100% | 5s | 2473084/2473084 | 5s
Saving... example-similar.json
Found 24324 similar matches.
```

**Comment by PeterShaggyNoble** [comment]
Great work, @darosh, thanks 😄

**Comment by Templarian** [comment]
This is really cool, but closing as it's not a priority at the moment.

Moving all issues over to the new repo.
