### ISSUE TITLE
Suggested Change to "Contact"

### ISSUE THREAD

**Issue by davelilly** [Templarian/MaterialDesign-Site#81]
Can you tell me if, under the SIL, Apache, and/or MIT licenses, Google's Material Design icons and/or the Community-generated Material Design icons can be used in commercial print materials that will be printed and either sold or used for marketing purposes?

**Comment by Templarian** [comment]
All of the licenses allow that kind of use. Perfectly fine. Just don't try and sell the icons themselves. 😉

Material Design Icons are used in print materials all the time. There are a lot of mediums for their use.

**Comment by Templarian** [comment]
By the way we have issue #2 tracking adding an FAQ to the http://dev.materialdesignicons.com/license page.

Probably could put all of this into easier to understand wording. Almost everything is allowed under these licenses. They are meant to be as open as possible.

**Comment by davelilly** [comment]
Thank you!! Super helpful to know!! Really appreciate the work you do and for getting back to me!
