### ISSUE TITLE
Flutter Support

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign-Site#85]

**Comment by Templarian** [comment]
Need a lot more details. Like Flutter documentation?

**Comment by ofekashery** [comment]
After search, It seems that someone has made support for this project.
[https://github.com/ziofat/material_design_icons_flutter](https://github.com/ziofat/material_design_icons_flutter)

I think you should talk to him and make it official

**Comment by Templarian** [comment]
They are using the font instead of the vectors which has me worried. Unless I'm looking into that source code wrong they would need to refactor it to use the SVG vector files. Including all the icons into a project is a bit overkill as we grow the library.

**Comment by ofekashery** [comment]
@ziofat

**Comment by ziofat** [comment]
In Flutter, developers use `Icon` class to show icons, which requires `IconData` defined with a glyph from a font. Providing this form of widgets can make the package as a drop-in replacement to Flutter built-in Material Design Icons.

SVG is not well supported by Flutter.  I think using a generated font as asset is the best solution for now.

**Comment by Templarian** [comment]
@ziofat Thanks for clarifying that for me. Yea, hopefully they add SVG path data as an alternative in the future, for now we'll just have the document how to drop in the font. 😸 

I'll work on adding placeholder pages this week/nav items. Then anyone can submit a quick PR with the content. 😃

**Comment by Templarian** [comment]
https://github.com/Pictogrammers/Icon-Site/issues/5

Pictogrammers will be where we manage all the site work in the future. This repository will be archived.
