### ISSUE TITLE
Update Links on Light History Page

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign-Site#86]
The icon & issue links on the [light history page](http://dev.materialdesignicons.com/history/light) need to be updated; they currently link to the base icon and main repo, respectively.

**Comment by Templarian** [comment]
With my ~3 weeks of vacation coming up I'm going to be working a lot on the website. Have a nice idea of how to handle these cases where we need separate documentation for regular/light.
