### ISSUE TITLE
Suggested Change to mdi.svg

### ISSUE THREAD

**Issue by dmosberger** [Templarian/MaterialDesign-Site#88]
mdi.svg doesn't have any viewBox attributes, which causes the icons to be displayed incorrectly when they're scaled to anything other than 24 pixels.  This is a problem when using the icons with `<mat-stepper>`, for example.

If the file could be generated such that all elements:

`  <g id="icon-name">...</g>`

are replaced with:

` <svg id="icon-name" viewBox="0 0 24 24">...</svg>`

all the scaling issues go away.

Here is an example of what `<mat-stepper>` looks like with the original mdi.svg:

![bad](https://user-images.githubusercontent.com/10587950/52151003-dd05b280-262e-11e9-93d5-4cb07604e843.png)

Here is what it looks like with the viewBox attribute included:

![good](https://user-images.githubusercontent.com/10587950/52151009-df680c80-262e-11e9-93e5-fd7de55c551d.png)

**Comment by Templarian** [comment]
@dmosberger What's this for exactly? Where are you getting "mdi.svg"?

**Comment by dmosberger** [comment]
From [dev.materialdesignicons.com](https://dev.materialdesignicons.com/getting-started)

**Comment by Templarian** [comment]
@dmosberger There are a lot of frameworks documented. More specifically? Sorry, I didn't write all of these docs, so not 100% familiar.

**Comment by dmosberger** [comment]
Sorry, the URL was incomplete: it's on the [Angular page](https://dev.materialdesignicons.com/getting-started/angular) of the getting-started section.  Look for "Angular 2+ Download for Angular Material 'mdi.svg'".

**Comment by Templarian** [comment]
Oh, hmm interesting. Yea, probably should just point to the NPM package and I can get rid of the legacy download link.

Really one should be using `@mdi/js` like react developers do. Including all of the icons is a very bad idea for most apps.

Is there a reason why one would ever use the download link instead of the `npm` package?

**Comment by dmosberger** [comment]
The reason I went the mdi.svg route is because it's not clear to me how, with @mdi/js, I could conveniently use an MDI icon in an Angular template.  It looks like you'd have to write a separate component for each icon used?

I agree that it'd be silly to include all unused icons.  I use a little python script to extract only the ones we actually use.  I see treeshaking should be able to do that automatically for @mdi/js, but I like being able to specify any icon with `<mat-icon svgIcon="...">`.  Is there a way to do this with @mdi/js?

**Comment by ofekashery** [comment]
I really agree with you @dmosberger

**Comment by Templarian** [comment]
By the way `@mdi/angular-material` was updated with a similar fix in the last release.

This was updated on the website also. Sorry, should have done this earlier, it was a relatively quick 1 minute change, but have been rather distracted.

Thanks for bringing this to my attention!

**Comment by dmosberger** [comment]
Thanks for fixing that!  I checked and confirmed that the new version works as expected.
