### ISSUE TITLE
Suggested Change to "Angular - Getting Started"

### ISSUE THREAD

**Issue by DayoAA** [Templarian/MaterialDesign-Site#92]
The import module of HttpModule has been deprecated. I am working on Angular 7 and had to use HttpClientModule (import { HttpClientModule } from '@angular/common/http';) in order for my application to load. I also had to place the Modules in the import instead of the @NgModule.

**Comment by Templarian** [comment]
Pictogrammers will be where we manage all the site work in the future. This repository will be archived.

https://github.com/Pictogrammers/Icon-Site/issues
