### ISSUE TITLE
Suggested Change to "Angular - Getting Started" Angular Material 2 SVG File

### ISSUE THREAD

**Issue by chriscurnow** [Templarian/MaterialDesign-Site#95]
Under **Angular Material**, the documentation says 
`Place the SVG file under your assets folder`

What SVG file?

**Comment by Templarian** [comment]
Made the link into a blue button. We offer the download as an option for those that don't use NPM. It also is generated from the DB directly so it includes the very latest WIP icons. Just be aware of that.

![image](https://user-images.githubusercontent.com/338885/58220048-ddf04c00-7cd2-11e9-9b85-94c1eaabb9a6.png)

**Comment by chriscurnow** [comment]
Thanks so much for the prompt response. I didn't expect an answer quite as quickly as that.

Now I understand.

What if I install the module via npm?

What do I import from `@mdi/angular-material`?

BTW: this is a fantastic project. I'll contribute whenever I can.

**Comment by Templarian** [comment]
https://www.npmjs.com/package/@mdi/angular-material

Good point I should probably link to the NPM page. I didn't actually write any of this. We just publish it as part of our releases.

**Comment by Templarian** [comment]
Updated!

Also, you got lucky I'm in the middle of working with one of our core members on some doc changes at the moment. Actually traveling for work a lot, so been a bit spotty. 😃

**Comment by chriscurnow** [comment]
Aha, yes that would be good.

Now I see _(and, as my mother used to say "said the blind man who couldn't see at all." 😸 )_
